
@SERVER_URL = http://127.0.0.1:8080
@COOKIE = LMaAy-2WDiLRcXayU7pBtCkgcqeNa1GT2Q5gVhdqRxs;;



### Get all events
GET {{SERVER_URL}}/ticket HTTP/1.1


### Create ticket
POST {{SERVER_URL}}/ticket/create/67b0b3539339f4a0b98bc932 HTTP/1.1
content-type: application/json

{

    "attendee_name": "Njabulo MKhwanazi",
    "attendee_email": "njabulo@email.com"
                 
}



### Redeem Ticket
GET {{SERVER_URL}}/ticket/redeem/TE865NHP HTTP/1.1



